spring.application.name=meu-projeto-springboot

spring.datasource.url=jdbc:postgresql://dpg-d9gjn3km0tmc73cb9sr0-a.oregon-postgres.render.com/produtos_elej
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.web.error.whitelabel.enabled=false
server.servlet.context-path=/
server.port=${PORT:8080}