spring.application.name=meu-projeto-springboot

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/meu_banco}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:012005}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.web.error.whitelabel.enabled=false
server.servlet.context-path=/
server.port=${PORT:8080}